#ifndef _POLYDATA_H_
#define _POLYDATA_H_


class Polydata {

private:
    GLuint vao; //Vertex array object
    GLuint vertBuffObj;
    GLuint normBuffObj;
    GLuint elmBuffObj;
    
    bool readyToRender; //True if it has been attached to a shader
    
    void initVBO(); //Generates new VBO's for first time use
    
public:
    limPolyData* lpd; //Polygon data generated by Teem
    bool isReadyToRender(); //Getter for above variable
    void bufferData(bool allocateNewBuffers);
    
}

class PolyDataInstance{
public:
    PolyData poly;
    glm::mat4 model; //Model matrix associated with a specific object in the scene
    
    //Used to extend functionality
    void (*prerender)(void*);
    void* prerenderData;
}

#endif